BEGIN
    INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES (1, 'Electronics');
    INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES (2, 'Furniture');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        NULL; -- Ignore duplicates
END;