BEGIN
    BEGIN
        INSERT INTO ORDER_STATUSES (STATUS_ID, STATUS_NAME) VALUES (1, 'PENDING');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO ORDER_STATUSES (STATUS_ID, STATUS_NAME) VALUES (2, 'CONFIRMED');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDER_STATUSES (STATUS_ID, STATUS_NAME) VALUES (3, 'CANCELLED');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;
END;
/
