BEGIN
    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (1, 101);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;
    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (1, 101);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; 
    END;


    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (1, 104);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; 
    END;



    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (1, 105);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; 
    END;

    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (2, 102);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (3, 103);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (4, 104);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (5, 105);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (6, 106);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (7, 107);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (8, 108);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (9, 109);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (10, 110);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;
END;
/
