BEGIN
    INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, ORDER_STATUS_ID, PAYMENTS_PAYMENT_ID, USERS_USER_ID) 
    VALUES (1, TO_TIMESTAMP('2024-11-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 201, 1);

    INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, ORDER_STATUS_ID, PAYMENTS_PAYMENT_ID, USERS_USER_ID) 
    VALUES (2, TO_TIMESTAMP('2024-11-02 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 202, 2);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        NULL; -- Ignore duplicates
END;