BEGIN
    BEGIN
        INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_STATUS, PAYMENT_DATE, PAYMENT_REF_ID, ORDERS_ORDER_ID) 
        VALUES (201, 'Completed', TO_TIMESTAMP('2024-11-01 10:30:00', 'YYYY-MM-DD HH24:MI:SS'), 10001, 1);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_STATUS, PAYMENT_DATE, PAYMENT_REF_ID, ORDERS_ORDER_ID) 
        VALUES (202, 'Pending', TO_TIMESTAMP('2024-11-02 11:15:00', 'YYYY-MM-DD HH24:MI:SS'), 10002, 2);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_STATUS, PAYMENT_DATE, PAYMENT_REF_ID, ORDERS_ORDER_ID) 
        VALUES (1004, 'Completed', TO_TIMESTAMP('2024-11-04 12:30:00', 'YYYY-MM-DD HH24:MI:SS'), 5004, 4);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_STATUS, PAYMENT_DATE, PAYMENT_REF_ID, ORDERS_ORDER_ID) 
        VALUES (1005, 'Pending', TO_TIMESTAMP('2024-11-05 14:50:00', 'YYYY-MM-DD HH24:MI:SS'), 5005, 5);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_STATUS, PAYMENT_DATE, PAYMENT_REF_ID, ORDERS_ORDER_ID) 
        VALUES (1006, 'Canceled', TO_TIMESTAMP('2024-11-06 16:45:00', 'YYYY-MM-DD HH24:MI:SS'), 5006, 6);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_STATUS, PAYMENT_DATE, PAYMENT_REF_ID, ORDERS_ORDER_ID) 
        VALUES (1007, 'Completed', TO_TIMESTAMP('2024-11-07 10:10:00', 'YYYY-MM-DD HH24:MI:SS'), 5007, 7);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_STATUS, PAYMENT_DATE, PAYMENT_REF_ID, ORDERS_ORDER_ID) 
        VALUES (1008, 'Pending', TO_TIMESTAMP('2024-11-08 13:30:00', 'YYYY-MM-DD HH24:MI:SS'), 5008, 8);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;
END;
/
