BEGIN
    BEGIN
        INSERT INTO PAYMENT_TYPES (PAYMENT_TYPE_ID, PAYMENT_TYPE_NAME) VALUES (1, 'Credit Card');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO PAYMENT_TYPES (PAYMENT_TYPE_ID, PAYMENT_TYPE_NAME) VALUES (2, 'PayPal');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;
END;
/
