-- Insert sample data into USER LOCATIONS table
BEGIN
    INSERT INTO USER_LOCATIONS (USERS_USER_ID, LOCATION_LOCATION_ID) VALUES (1, 1);
    INSERT INTO USER_LOCATIONS (USERS_USER_ID, LOCATION_LOCATION_ID) VALUES (2, 2);
    INSERT INTO USER_LOCATIONS (USERS_USER_ID, LOCATION_LOCATION_ID) VALUES (3, 3);
    INSERT INTO USER_LOCATIONS (USERS_USER_ID, LOCATION_LOCATION_ID) VALUES (4, 4);
    INSERT INTO USER_LOCATIONS (USERS_USER_ID, LOCATION_LOCATION_ID) VALUES (5, 5);
    INSERT INTO USER_LOCATIONS (USERS_USER_ID, LOCATION_LOCATION_ID) VALUES (6, 6);
    INSERT INTO USER_LOCATIONS (USERS_USER_ID, LOCATION_LOCATION_ID) VALUES (7, 7);
    INSERT INTO USER_LOCATIONS (USERS_USER_ID, LOCATION_LOCATION_ID) VALUES (8, 8);
    INSERT INTO USER_LOCATIONS (USERS_USER_ID, LOCATION_LOCATION_ID) VALUES (9, 9);
    INSERT INTO USER_LOCATIONS (USERS_USER_ID, LOCATION_LOCATION_ID) VALUES (10, 10);
    INSERT INTO USER_LOCATIONS (USERS_USER_ID, LOCATION_LOCATION_ID) VALUES (11, 11);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        NULL; -- Ignore duplicates
END;