BEGIN
    INSERT INTO PAYMENT_TYPES (PAYMENT_TYPE_ID, PAYMENT_TYPE_NAME) VALUES (1, 'Credit Card');
    INSERT INTO PAYMENT_TYPES (PAYMENT_TYPE_ID, PAYMENT_TYPE_NAME) VALUES (2, 'PayPal');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        NULL; -- Ignore duplicates
END;