BEGIN
    BEGIN
        INSERT INTO LOCATIONS(LOCATION_ID, LATITUDE, LONGITUDE, ADDRESS, CITY_CODE, ZIP_CODE, LOCATION_TYPE, WAREHOUSE_WAREHOUSE_ID) 
        VALUES (1, 42.36, -71.05, '123 Main St', 100, '02118', 'user', NULL);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO LOCATIONS(LOCATION_ID, LATITUDE, LONGITUDE, ADDRESS, CITY_CODE, ZIP_CODE, LOCATION_TYPE, WAREHOUSE_WAREHOUSE_ID) 
        VALUES (2, 45.36, -68.05, '315 Centre street', 100, '02118', 'warehouse', 1);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;
END;
/
