BEGIN
    BEGIN
        INSERT INTO WAREHOUSE (WAREHOUSE_ID, IS_ACTIVE, OPENING_TIME, CLOSING_TIME, LOCATION_LOCATION_ID, CREATED_AT, UPDATED_AT) 
        VALUES (1, 'Y', '08:00', '20:00', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;
END;
/
