-- Insert sample data into USERS table
INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (1, 'True', 1);
INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (2, 'True', 2);
INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (3, 'True', 3);
INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (4, 'True', 4);
INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (5, 'True', 5);
INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (6, 'True', 6);
INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (7, 'True', 7);
INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (8, 'True', 8);
INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (9, 'True', 9);
INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (10, 'True', 10);
INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (11, 'True', 11);