BEGIN
    BEGIN
        INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (1, 101);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;
END;
/
