BEGIN
    BEGIN
        INSERT INTO PAYMENT_TYPES (PAYMENT_TYPE_ID, PAYMENT_TYPE_NAME) VALUES (1, 'CREDIT');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO PAYMENT_TYPES (PAYMENT_TYPE_ID, PAYMENT_TYPE_NAME) VALUES (2, 'PAYPAL');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO PAYMENT_TYPES (PAYMENT_TYPE_ID, PAYMENT_TYPE_NAME) VALUES (3, 'DEBIT');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;
END;
/
