BEGIN
    BEGIN
        INSERT INTO LOCATIONS(LOCATION_ID, LATITUDE, LONGITUDE, ADDRESS, CITY_CODE, ZIP_CODE, LOCATION_TYPE, WAREHOUSE_WAREHOUSE_ID) 
        VALUES (1, 42.36, -71.05, '123 Main St', 100, '02118', 'user', NULL);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO LOCATIONS(LOCATION_ID, LATITUDE, LONGITUDE, ADDRESS, CITY_CODE, ZIP_CODE, LOCATION_TYPE, WAREHOUSE_WAREHOUSE_ID) 
        VALUES (2, 52.36, -79.05, '321 Ruggles St', 100, '02129', 'user', NULL);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO LOCATIONS(LOCATION_ID, LATITUDE, LONGITUDE, ADDRESS, CITY_CODE, ZIP_CODE, LOCATION_TYPE, WAREHOUSE_WAREHOUSE_ID) 
        VALUES (3, 108.36, -78.05, '132 Roxbery St', 100, '02119', 'user', NULL);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO LOCATIONS(LOCATION_ID, LATITUDE, LONGITUDE, ADDRESS, CITY_CODE, ZIP_CODE, LOCATION_TYPE, WAREHOUSE_WAREHOUSE_ID) 
        VALUES (4, 45.36, -68.05, '315 Centre street', 100, '02118', 'warehouse', 1);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO LOCATIONS(LOCATION_ID, LATITUDE, LONGITUDE, ADDRESS, CITY_CODE, ZIP_CODE, LOCATION_TYPE, WAREHOUSE_WAREHOUSE_ID) 
        VALUES (5, 98.36, -78.05, '315 Roxbery street', 100, '02122', 'warehouse', 2);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;
    
END;
/
