BEGIN
    INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_TYPE_ID, ITEM_QUANTITY, MRP, SELLING_PRICE, DISCOUNTS, WAREHOUSE_WAREHOUSE_ID, IS_ACTIVE) 
    VALUES (101, 'Smartphone', 1, 50, 700, 650, 5.00, 1, 'Y');

    INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_TYPE_ID, ITEM_QUANTITY, MRP, SELLING_PRICE, DISCOUNTS, WAREHOUSE_WAREHOUSE_ID, IS_ACTIVE) 
    VALUES (102, 'Sofa', 2, 20, 1500, 1200, 10.00, 2, 'Y');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        NULL; -- Ignore duplicates
END;