BEGIN
    BEGIN
        INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_STATUS, PAYMENT_DATE, PAYMENT_REF_ID, ORDERS_ORDER_ID) 
        VALUES (1, 'COMPLETED', CURRENT_TIMESTAMP, 1, 1);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_STATUS, PAYMENT_DATE, PAYMENT_REF_ID, ORDERS_ORDER_ID) 
        VALUES (2, 'PENDING', CURRENT_TIMESTAMP, 1, 1);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO PAYMENTS (PAYMENT_ID, PAYMENT_STATUS, PAYMENT_DATE, PAYMENT_REF_ID, ORDERS_ORDER_ID) 
        VALUES (3, 'FAILED', CURRENT_TIMESTAMP, 1, 1);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;
END;
/