BEGIN
    BEGIN
        INSERT INTO WAREHOUSE (WAREHOUSE_ID, IS_ACTIVE, OPENING_TIME, CLOSING_TIME, LOCATION_LOCATION_ID, CREATED_AT, UPDATED_AT) 
        VALUES (1, 'Y', '08:00', '20:00', 1, TO_TIMESTAMP('2024-10-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-11-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS'));
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO WAREHOUSE (WAREHOUSE_ID, IS_ACTIVE, OPENING_TIME, CLOSING_TIME, LOCATION_LOCATION_ID, CREATED_AT, UPDATED_AT) 
        VALUES (2, 'Y', '09:00', '18:00', 2, TO_TIMESTAMP('2024-10-02 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2024-11-02 10:00:00', 'YYYY-MM-DD HH24:MI:SS'));
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;
    BEGIN
        INSERT INTO WAREHOUSE (WAREHOUSE_ID, IS_ACTIVE, OPENING_TIME, CLOSING_TIME, LOCATION_LOCATION_ID, CREATED_AT, UPDATED_AT) 
        VALUES ( 3, 'Y', '08:00', '19:00', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;
END;
/
