-- Insert sample data into USERS table
BEGIN
    BEGIN
        INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (1, 'Y', 1);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (2, 'Y', 2);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (3, 'Y', 3);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (4, 'Y', 4);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (5, 'Y', 5);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (6, 'Y', 6);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (7, 'Y', 7);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (8, 'Y', 8);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (9, 'Y', 9);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (10, 'Y', 10);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (11, 'Y', 11);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;
END;
/
