BEGIN
    INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (1, 101);
    INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (2, 102);
    INSERT INTO ORDER_PRODUCTS (ORDERS_ORDER_ID, PRODUCTS_PRODUCT_ID) VALUES (3, 103);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        NULL; -- Ignore duplicates
END;
