BEGIN
    BEGIN
        INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, ORDER_STATUS_ID, PAYMENTS_PAYMENT_ID, USERS_USER_ID) 
        VALUES (1, TO_TIMESTAMP('2024-11-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 201, 1);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, ORDER_STATUS_ID, PAYMENTS_PAYMENT_ID, USERS_USER_ID) 
        VALUES (2, TO_TIMESTAMP('2024-11-02 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 202, 2);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, ORDER_STATUS_ID, PAYMENTS_PAYMENT_ID, USERS_USER_ID) 
        VALUES (3, TO_TIMESTAMP('2024-11-03 15:45:00', 'YYYY-MM-DD HH24:MI:SS'), 3, 1003, 3);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, ORDER_STATUS_ID, PAYMENTS_PAYMENT_ID, USERS_USER_ID) 
        VALUES (4, TO_TIMESTAMP('2024-11-04 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 1, 1004, 4);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, ORDER_STATUS_ID, PAYMENTS_PAYMENT_ID, USERS_USER_ID) 
        VALUES (5, TO_TIMESTAMP('2024-11-05 14:20:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 1005, 5);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, ORDER_STATUS_ID, PAYMENTS_PAYMENT_ID, USERS_USER_ID) 
        VALUES (6, TO_TIMESTAMP('2024-11-06 16:30:00', 'YYYY-MM-DD HH24:MI:SS'), 3, 1006, 6);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, ORDER_STATUS_ID, PAYMENTS_PAYMENT_ID, USERS_USER_ID) 
        VALUES (7, TO_TIMESTAMP('2024-11-07 09:45:00', 'YYYY-MM-DD HH24:MI:SS'), 3, 1007, 7);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO ORDERS (ORDER_ID, ORDER_DATE, ORDER_STATUS_ID, PAYMENTS_PAYMENT_ID, USERS_USER_ID) 
        VALUES (8, TO_TIMESTAMP('2024-11-08 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), 2, 1008, 8);
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;
END;
/
