-- Insert sample data into USERS table
BEGIN
    INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (1, 'Y', 1);
    INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (2, 'Y', 2);
    INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (3, 'Y', 3);
    INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (4, 'Y', 4);
    INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (5, 'Y', 5);
    INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (6, 'Y', 6);
    INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (7, 'Y', 7);
    INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (8, 'Y', 8);
    INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (9, 'Y', 9);
    INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (10, 'Y', 10);
    INSERT INTO "USER18GP"."USERS" (USER_ID, IS_ACTIVE, CONTACT_ID) VALUES (11, 'Y', 11);
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        NULL; -- Ignore duplicates
END;