BEGIN
    BEGIN
        INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_TYPE_ID, ITEM_QUANTITY, MRP, SELLING_PRICE, DISCOUNTS, WAREHOUSE_WAREHOUSE_ID, IS_ACTIVE) 
        VALUES (1, 'Lays Sour and Cream', 1, 100, 5, 4, 1.0, 1, 'Y');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_TYPE_ID, ITEM_QUANTITY, MRP, SELLING_PRICE, DISCOUNTS, WAREHOUSE_WAREHOUSE_ID, IS_ACTIVE) 
        VALUES (2, 'Lays BBQ', 1, 100, 6, 5, 1.0, 1, 'Y');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_TYPE_ID, ITEM_QUANTITY, MRP, SELLING_PRICE, DISCOUNTS, WAREHOUSE_WAREHOUSE_ID, IS_ACTIVE) 
        VALUES (3, 'Milk', 2, 50, 3, 2, 1.0, 1, 'Y');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_TYPE_ID, ITEM_QUANTITY, MRP, SELLING_PRICE, DISCOUNTS, WAREHOUSE_WAREHOUSE_ID, IS_ACTIVE) 
        VALUES (4, 'Bread', 2, 50, 4, 3, 1.0, 2, 'Y');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;

    BEGIN
        INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, CATEGORY_TYPE_ID, ITEM_QUANTITY, MRP, SELLING_PRICE, DISCOUNTS, WAREHOUSE_WAREHOUSE_ID, IS_ACTIVE) 
        VALUES (5, 'Apple', 3, 50, 8, 6, 2.0, 2, 'Y');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate
    END;
END;
/
