BEGIN
    BEGIN
        INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES (1, 'Electronics');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL; -- Ignore duplicate, proceed with next insert
    END;

    BEGIN
        INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES (2, 'Furniture');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES (3, 'Clothing');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES (4, 'Toys');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES (5, 'Books');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES (6, 'Groceries');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES (7, 'Sports');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES (8, 'Beauty');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES (9, 'Automotive');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;

    BEGIN
        INSERT INTO CATEGORIES (CATEGORY_ID, CATEGORY_NAME) VALUES (10, 'Health');
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            NULL;
    END;
END;
/
