@create_categories.sql
@create_locations.sql
@create_orderProducts.sql
@create_orders.sql
@create_orderStatus.sql
@create_payments.sql
@create_paymentTypes.sql
@create_products.sql
@create_roles.sql
@create_useLocations.sql
@create_users.sql
@create_warehouse.sql