BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "USER18GP"."ROLES" CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      -- Ignore the error if the table does not exist
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE "USER18GP"."ROLES" 
   (	"ROLE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ROLE_TYPES" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"USERS_USER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "ROLES_USERS_FK" FOREIGN KEY ("USERS_USER_ID")
	  REFERENCES "USER18GP"."USERS" ("USER_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  CREATE UNIQUE INDEX "USER18GP"."ROLES_PK" ON "USER18GP"."ROLES" ("ROLE_ID") 
  ;
ALTER TABLE "USER18GP"."ROLES" ADD CONSTRAINT "ROLES_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX "USER18GP"."ROLES_PK"  ENABLE;
