CREATE TABLE "USER18GP"."CONTACTS" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"FIRST_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"LAST_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"EMAIL_ID" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PHONE_NUM" VARCHAR2(10) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"USERS_USER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "CONTACTS_USERS_FK" FOREIGN KEY ("USERS_USER_ID")
	  REFERENCES "USER18GP"."USERS" ("USER_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  CREATE UNIQUE INDEX "USER18GP"."CONTACT_PK" ON "USER18GP"."CONTACTS" ("ID") 
  ;
ALTER TABLE "USER18GP"."CONTACTS" ADD CONSTRAINT "CONTACT_PK" PRIMARY KEY ("ID")
  USING INDEX "USER18GP"."CONTACT_PK"  ENABLE;
