BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "USER18GP"."ORDER_PRODUCTS" CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      -- Ignore the error if the table does not exist
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE "USER18GP"."ORDER_PRODUCTS" 
   (	"ORDERS_ORDER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRODUCTS_PRODUCT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "ORDER_PRODUCTS_ORDERS_FK" FOREIGN KEY ("ORDERS_ORDER_ID")
	  REFERENCES "USER18GP"."ORDERS" ("ORDER_ID") ENABLE, 
	 CONSTRAINT "ORDER_PRODUCTS_PRODUCTS_FK" FOREIGN KEY ("PRODUCTS_PRODUCT_ID")
	  REFERENCES "USER18GP"."PRODUCTS" ("PRODUCT_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  CREATE UNIQUE INDEX "USER18GP"."ORDER_PRODUCTS_PK" ON "USER18GP"."ORDER_PRODUCTS" ("ORDERS_ORDER_ID", "PRODUCTS_PRODUCT_ID") 
  ;
ALTER TABLE "USER18GP"."ORDER_PRODUCTS" ADD CONSTRAINT "ORDER_PRODUCTS_PK" PRIMARY KEY ("ORDERS_ORDER_ID", "PRODUCTS_PRODUCT_ID")
  USING INDEX "USER18GP"."ORDER_PRODUCTS_PK"  ENABLE;
