BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "USER18GP"."ORDER_STATUSES" CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      -- Ignore the error if the table does not exist
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE "USER18GP"."ORDER_STATUSES" 
   (	"STATUS_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"STATUS_NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "ORDER_STATUSES_PK" PRIMARY KEY ("STATUS_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "ORDER_STATUSES_STATUS_NAME_UN" UNIQUE ("STATUS_NAME")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
