BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "USER18GP"."USER_LOCATIONS" CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      -- Ignore the error if the table does not exist
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE "USER18GP"."USER_LOCATIONS" 
   (	"USERS_USER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"LOCATION_LOCATION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "USER_LOCATIONS_LOCATION_FK" FOREIGN KEY ("LOCATION_LOCATION_ID")
	  REFERENCES "USER18GP"."LOCATIONS" ("LOCATION_ID") ENABLE, 
	 CONSTRAINT "USER_LOCATIONS_USERS_FK" FOREIGN KEY ("USERS_USER_ID")
	  REFERENCES "USER18GP"."USERS" ("USER_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  CREATE UNIQUE INDEX "USER18GP"."USER_LOCATIONS_PK" ON "USER18GP"."USER_LOCATIONS" ("USERS_USER_ID", "LOCATION_LOCATION_ID") 
  ;
ALTER TABLE "USER18GP"."USER_LOCATIONS" ADD CONSTRAINT "USER_LOCATIONS_PK" PRIMARY KEY ("USERS_USER_ID", "LOCATION_LOCATION_ID")
  USING INDEX "USER18GP"."USER_LOCATIONS_PK"  ENABLE;
