BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "USER18GP"."CATEGORIES" CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      -- Ignore the error if the table does not exist
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE "USER18GP"."CATEGORIES" 
   (	"CATEGORY_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CATEGORY_NAME" VARCHAR2(100) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "CATEGORIES_PK" PRIMARY KEY ("CATEGORY_ID")
      USING INDEX ENABLE, 
	 CONSTRAINT "CATEGORIES_CATEGORY_NAME_UN" UNIQUE ("CATEGORY_NAME")
      USING INDEX ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP";