BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "USER18GP"."WAREHOUSE" CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      -- Ignore the error if the table does not exist
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE "USER18GP"."WAREHOUSE" 
   (	"WAREHOUSE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"IS_ACTIVE" CHAR(1) COLLATE "USING_NLS_COMP", 
	"OPENING_TIME" VARCHAR2(5) COLLATE "USING_NLS_COMP", 
	"CLOSING_TIME" VARCHAR2(5) COLLATE "USING_NLS_COMP", 
	"LOCATION_LOCATION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT current_timestamp, 
	"UPDATED_AT" TIMESTAMP (6), 
	 CHECK (REGEXP_LIKE (opening_time, '^([01][0-9]|2[0-3]):[0-5][0-9]$')) ENABLE, 
	 CHECK (REGEXP_LIKE (closing_time, '^([01][0-9]|2[0-3]):[0-5][0-9]$')) ENABLE, 
	 CHECK (is_active IN ('N', 'Y')) ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  CREATE UNIQUE INDEX "USER18GP"."WAREHOUSE_PK" ON "USER18GP"."WAREHOUSE" ("WAREHOUSE_ID") 
  ;
ALTER TABLE "USER18GP"."WAREHOUSE" ADD CONSTRAINT "WAREHOUSE_PK" PRIMARY KEY ("WAREHOUSE_ID")
  USING INDEX "USER18GP"."WAREHOUSE_PK"  ENABLE;
