CREATE TABLE "USER18GP"."PAYMENTS" 
   (	"PAYMENT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PAYMENT_STATUS" VARCHAR2(50 CHAR) COLLATE "USING_NLS_COMP", 
	"PAYMENT_DATE" TIMESTAMP (0), 
	"PAYMENT_REF_ID" NUMBER, 
	"ORDERS_ORDER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "PAYMENTS_ORDERS_FK" FOREIGN KEY ("ORDERS_ORDER_ID")
	  REFERENCES "USER18GP"."ORDERS" ("ORDER_ID") ENABLE, 
	 CONSTRAINT "PAYMENTS_TYPE_FK" FOREIGN KEY ("PAYMENT_REF_ID")
	  REFERENCES "USER18GP"."PAYMENT_TYPES" ("PAYMENT_TYPE_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  CREATE UNIQUE INDEX "USER18GP"."PAYMENTS_PK" ON "USER18GP"."PAYMENTS" ("PAYMENT_ID") 
  ;
ALTER TABLE "USER18GP"."PAYMENTS" ADD CONSTRAINT "PAYMENTS_PK" PRIMARY KEY ("PAYMENT_ID")
  USING INDEX "USER18GP"."PAYMENTS_PK"  ENABLE;
