CREATE TABLE "USER18GP"."PRODUCTS" 
   (	"PRODUCT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(100 CHAR) COLLATE "USING_NLS_COMP", 
	"CATEGORY_TYPE_ID" NUMBER(*,0), 
	"ITEM_QUANTITY" NUMBER, 
	"MRP" NUMBER, 
	"SELLING_PRICE" NUMBER, 
	"DISCOUNTS" NUMBER(2,2), 
	"WAREHOUSE_WAREHOUSE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"IS_ACTIVE" CHAR(1) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "PRODUCTS_WAREHOUSE_FK" FOREIGN KEY ("WAREHOUSE_WAREHOUSE_ID")
	  REFERENCES "USER18GP"."WAREHOUSE" ("WAREHOUSE_ID") ENABLE, 
	 CONSTRAINT "PRODUCTS_CATEGORY_FK" FOREIGN KEY ("CATEGORY_TYPE_ID")
	  REFERENCES "USER18GP"."CATEGORIES" ("CATEGORY_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  CREATE UNIQUE INDEX "USER18GP"."PRODUCTS_PK" ON "USER18GP"."PRODUCTS" ("PRODUCT_ID") 
  ;
ALTER TABLE "USER18GP"."PRODUCTS" ADD CONSTRAINT "PRODUCTS_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX "USER18GP"."PRODUCTS_PK"  ENABLE;
