BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE "USER18GP"."LOCATIONS" CASCADE CONSTRAINTS';
   DBMS_OUTPUT.PUT_LINE('Table "LOCATIONS" dropped successfully.');
EXCEPTION
   WHEN OTHERS THEN
      -- Ignore the error if the table does not exist
      IF SQLCODE != -942 THEN
         RAISE;
		 ELSE
            DBMS_OUTPUT.PUT_LINE('Table "LOCATIONS" does not exist, skipping drop.');
      END IF;
END;
/

CREATE TABLE "USER18GP"."LOCATIONS" 
   (	"LOCATION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	"ADDRESS" VARCHAR2(64 CHAR) COLLATE "USING_NLS_COMP", 
	"CITY_CODE" NUMBER(*,0), 
	"ZIP_CODE" VARCHAR2(10 CHAR) COLLATE "USING_NLS_COMP", 
	"LOCATION_TYPE" VARCHAR2(10 CHAR) COLLATE "USING_NLS_COMP", 
	"WAREHOUSE_WAREHOUSE_ID" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "LOCATIONS_WAREHOUSE_FK" FOREIGN KEY ("WAREHOUSE_WAREHOUSE_ID")
	  REFERENCES "USER18GP"."WAREHOUSE" ("WAREHOUSE_ID") ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;
  CREATE UNIQUE INDEX "USER18GP"."LOCATION_PK" ON "USER18GP"."LOCATIONS" ("LOCATION_ID") 
  ;
ALTER TABLE "USER18GP"."LOCATIONS" ADD CONSTRAINT "LOCATION_PK" PRIMARY KEY ("LOCATION_ID")
  USING INDEX "USER18GP"."LOCATION_PK"  ENABLE;